apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-backend
      tier: backend
  template:
    metadata:
      labels:
         app: kube-backend
         tier: backend
    spec:
      containers:
        - name: kube-backend
          image: rbeniwal26119/kube-backend:latest
