apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: rbeniwal26119/kube-user-api-node:latest
          env:
            - name: AUTH_ADDRESS
              value: localhost
            # - name: AUTH_SERVICE_SERVICE_HOST # this is the service name automatically created by kubernetes
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: status.hostIP
        - name: auth
          image: rbeniwal26119/kube-auth-api-node:latest
          