# Generated by Django 4.1.4 on 2023-01-30 08:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_info',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
