apiVersion: v1
kind: Service
metadata:
  name: kube-backend-service
spec:
  selector:
    app: kube-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-backend
  template:
    metadata:
      labels:
        app: kube-backend
    spec:
      containers:
        - name: kube-backend
          image: rbeniwal26119/kube-backend:latest
          volumeMounts:
            - name: kube-backend-store-user
              mountPath: /docker_app/logged_details
      volumes:
        - name: kube-backend-store-user
          persistentVolumeClaim:
            claimName: host-pvc
         
          # emptyDir: {} # if pod removed then data removed so data will be lost in case multiple replicas
          # hostPath: # Share data between multiple pods on single node and pick initial data from host
          #   path: /data/
          #   type: DirectoryOrCreate

