apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: kube-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
    - protocol: UDP
      port: 8001
      targetPort: 8001
      name: https
  type: LoadBalancer